server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  interface:
    hostname: localhost

spring:
  application:
    name: Gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enable: true
      routes:
      #- id: user-service  ## nombre del servicio
      #  uri: lb://user-service ## label con el nombre del servicio
      #  predicates:
      #    - Path=/user/**  ##Ruta de la aplicacion

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/spring-boot-realm-dev/protocol/openid-connect/auth
            user-info-uri: http://localhost:9090/realms/spring-boot-realm-dev/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/spring-boot-realm-dev/protocol/openid-connect/token
        registration:
          client-name:
            provider: keycloak
            client-id: spring-client-api-rest
            client-secret: W60FXYjavQApz5auMADJTh7WNmqG1znA
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spring-client-api-rest"